# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://cxromos.com
title: CxRomos
email: danijel.kecman@gmail.com
author: Danijel Kecman
description: > # "CxRomos LLC."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/cxromos
  - title: github
    url: https://github.com/cxromos
  - title: linkedin
    url: https://www.linkedin.com/in/danijelkecman
